### PR TITLE
Fix #140 - Resolve gpus TypeError

### LINKED ISSUE #140: Unexpected keyword argument:  gpus
Error:  __init__() got an unexpected keyword argument 'gpus'
TypeError in marathon.models.base in from_json

This error starting occurring after upgrading from DCOS 1.7 to 1.8, which comes packaged with Marathon 1.3.

### PR DESCRIPTION
**Pull request by mbeacom**
Resolves #140 - `gpus` TypeError

### CODE REVIEW

**Comment by solarkennedy** [comment]
Ty for the PR. It just feel kinda yucky that it breaks on an unreleased, undocumented thing :(

Granted, this would have been caught when we upgrade the travis matrix to include marathon 1.3 when it comes out!

**Comment by mbeacom** [comment]
@solarkennedy Thank you for merging this ahead of the release!  We recently upgraded to the DC/OS 1.8 release and we ran into the error in the client.  Figured I would submit the PR!

Thanks again
