### ISSUE TITLE
Unexpected keyword argument:  gpus

### ISSUE THREAD

**Issue by mbeacom** [thefactory/marathon-python#140]
Error:  __init__() got an unexpected keyword argument 'gpus'
TypeError in marathon.models.base in from_json

This error starting occurring after upgrading from DCOS 1.7 to 1.8, which comes packaged with Marathon 1.3.

**Comment by solarkennedy** [comment]
But they haven't even released it yet publicly?
https://github.com/mesosphere/marathon/releases
